customhost = "mydatabase12.coogycpqkptq.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "mydatabase12"
custombucket = "my-project2-bucket12"
customregion = "us-east-1"
